ERROR 2024-10-23 15:04:47,824 log Internal Server Error: /factoryoutlet/barcode/generate-barcode/
Traceback (most recent call last):
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode/views.py", line 41, in post
    barcode_print_init(barcodes,number_of_barcodes,pname,psize,ptype,seller,pamount)
  File "/factoryoutlet/factoryoutlet/barcode_print/views.py", line 13, in barcode_print_init
    error_response = return_400_if_object_found(BarcodeT, number_of_barcodes=number_of_barcodes, pname=pname, psize=psize, ptype=ptype, seller=seller, pamount=pamount)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode_print/utils.py", line 5, in return_400_if_object_found
    obj = model.objects.filter(**filters).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'pamount' into field. Choices are: Approval, dog, gen_slot, id, last_barcode, number_of_barcodes, print_slot, print_status, start_barcode
ERROR 2024-10-23 15:04:47,833 basehttp "POST /factoryoutlet/barcode/generate-barcode/ HTTP/1.0" 500 151248
ERROR 2024-10-23 15:25:10,661 log Internal Server Error: /factoryoutlet/barcode/generate-barcode/
Traceback (most recent call last):
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode/views.py", line 41, in post
    barcode_print_init(barcodes,number_of_barcodes,pname,psize,ptype,seller,pamount)
  File "/factoryoutlet/factoryoutlet/barcode_print/views.py", line 14, in barcode_print_init
    error_response = return_400_if_object_found(TypeT, number_of_barcodes=number_of_barcodes, pname=pname, psize=psize, ptype=ptype, seller=seller, pamount=pamount)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode_print/utils.py", line 5, in return_400_if_object_found
    obj = model.objects.filter(**filters).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'number_of_barcodes' into field. Choices are: b_type, eid, eid_id, last_barcode, last_processed_date, lat_pid, pamount, pname, pseller, psize, ptype
ERROR 2024-10-23 15:25:10,668 basehttp "POST /factoryoutlet/barcode/generate-barcode/ HTTP/1.0" 500 151119
ERROR 2024-10-23 15:45:02,571 log Internal Server Error: /factoryoutlet/barcode/generate-barcode/
Traceback (most recent call last):
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode/views.py", line 41, in post
    barcode_print_init(barcodes,number_of_barcodes,pname,psize,ptype,seller,pamount)
  File "/factoryoutlet/factoryoutlet/barcode_print/views.py", line 14, in barcode_print_init
    error_response = return_400_if_object_found(TypeT, number_of_barcodes,pname=pname, psize=psize, ptype=ptype, seller=seller, pamount=pamount)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode_print/utils.py", line 5, in return_400_if_object_found
    obj = model.objects.filter(**filters).first()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'seller' into field. Choices are: b_type, eid, eid_id, last_barcode, last_processed_date, lat_pid, pamount, pname, pseller, psize, ptype
ERROR 2024-10-23 15:45:02,578 basehttp "POST /factoryoutlet/barcode/generate-barcode/ HTTP/1.0" 500 151565
ERROR 2024-10-23 15:51:40,240 log Internal Server Error: /factoryoutlet/barcode/generate-barcode/
Traceback (most recent call last):
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode/views.py", line 41, in post
    barcode_print_init(barcodes,number_of_barcodes,pname,psize,ptype,pseller,pamount)
                                                                     ^^^^^^^
NameError: name 'pseller' is not defined. Did you mean: 'seller'?
ERROR 2024-10-23 15:51:40,245 basehttp "POST /factoryoutlet/barcode/generate-barcode/ HTTP/1.0" 500 94550
ERROR 2024-10-23 15:55:09,749 log Internal Server Error: /factoryoutlet/barcode/generate-barcode/
Traceback (most recent call last):
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode/views.py", line 41, in post
    barcode_print_init(barcodes,number_of_barcodes,pname,psize,ptype,seller,pamount)
  File "/factoryoutlet/factoryoutlet/barcode_print/views.py", line 14, in barcode_print_init
    error_response = return_400_if_object_found(TypeT, number_of_barcodes,pname=pname, psize=psize, ptype=ptype, pseller=seller, pamount=pamount)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode_print/utils.py", line 6, in return_400_if_object_found
    no_of_barcode_calculation=(obj.last_barcode-obj.start_barcode)
                                                ^^^^^^^^^^^^^^^^^
AttributeError: 'TypeT' object has no attribute 'start_barcode'. Did you mean: 'last_barcode'?
ERROR 2024-10-23 15:55:09,758 basehttp "POST /factoryoutlet/barcode/generate-barcode/ HTTP/1.0" 500 104883
ERROR 2024-10-23 15:59:47,607 log Internal Server Error: /factoryoutlet/barcode/generate-barcode/
Traceback (most recent call last):
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode/views.py", line 41, in post
    barcode_print_init(barcodes,number_of_barcodes,pname,psize,ptype,seller,pamount)
  File "/factoryoutlet/factoryoutlet/barcode_print/views.py", line 14, in barcode_print_init
    error_response = return_400_if_object_found(TypeT, BarcodeT, number_of_barcodes,pname=pname, psize=psize, ptype=ptype, pseller=seller, pamount=pamount)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/barcode_print/utils.py", line 6, in return_400_if_object_found
    obj1 = model2.objects.filter(**filters).first()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1491, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1303, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/factoryoutlet/factoryoutlet/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1768, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'pamount' into field. Choices are: Approval, dog, gen_slot, id, last_barcode, number_of_barcodes, print_slot, print_status, start_barcode
ERROR 2024-10-23 15:59:47,618 basehttp "POST /factoryoutlet/barcode/generate-barcode/ HTTP/1.0" 500 151204
